"""empty message

Revision ID: 119f2c7c2bf7
Revises: 
Create Date: 2025-05-02 23:39:35.325925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '119f2c7c2bf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practitioner_roles', schema=None) as batch_op:
        batch_op.drop_column('organization')
        batch_op.drop_column('specialty')

    with op.batch_alter_table('practitioners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=11), nullable=True))
        batch_op.create_unique_constraint(None, ['contact_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practitioners', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('contact_number')

    with op.batch_alter_table('practitioner_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('organization', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
